#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright © 2016-2025 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones: [ us-east-1a,us-east-1b,us-east-1c ]

metadata:
  name: tbmq
  region: us-east-1
  version: "1.31"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: tbmq-node
    instanceType: c7a.large
    desiredCapacity: 2
    maxSize: 2
    minSize: 0
    labels: { role: tbmq }
    privateNetworking: true
    volumeType: gp3
    volumeSize: 20

  - name: tbmq-ie
    instanceType: c7a.medium
    desiredCapacity: 2
    maxSize: 2
    minSize: 0
    labels: { role: tbmq-ie }
    privateNetworking: true
    volumeType: gp3
    volumeSize: 20

  - name: tbmq-kafka
    instanceType: c7a.large
    desiredCapacity: 3
    maxSize: 3
    minSize: 0
    labels: { role: kafka }
    privateNetworking: true
    volumeType: gp3
    volumeSize: 20

  - name: tbmq-redis
    instanceType: c7a.medium
    desiredCapacity: 6
    maxSize: 6
    minSize: 0
    labels: { role: redis }
    privateNetworking: true
    volumeType: gp3
    volumeSize: 20

  # Optional group. You can safely remove this section if:
  #   - You’re using Amazon RDS or an existing PostgreSQL service.
  #   - You want to keep your database outside the EKS cluster.
  - name: tbmq-postgresql
    instanceType: c7a.large
    desiredCapacity: 1
    maxSize: 1
    minSize: 0
    labels: { role: postgresql }
    volumeType: gp3
    volumeSize: 20

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
  - name: aws-efs-csi-driver
    wellKnownPolicies:
      efsCSIController: true
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    resolveConflicts: overwrite
  - name: coredns
    version: latest
    configurationValues: "{\"replicaCount\":3}"
    resolveConflicts: overwrite
  - name: kube-proxy
    version: latest
    resolveConflicts: overwrite
